# Generated by Django 2.0 on 2019-06-10 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.Curso')),
                ('iduser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoraEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_entrada', models.CharField(max_length=50, unique=True)),
                ('h_entrada', models.DateTimeField(blank=True, null=True)),
                ('f_entrada', models.CharField(blank=True, max_length=50, null=True)),
                ('h_entrada_str', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entrada', models.TimeField(blank=True, null=True)),
                ('time_salida', models.TimeField(blank=True, null=True)),
                ('actividad', models.CharField(max_length=50)),
                ('firma', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.CharField(max_length=50)),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.Curso')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoraSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_salida', models.CharField(max_length=50, unique=True)),
                ('h_salida', models.DateTimeField(blank=True, null=True)),
                ('f_salida', models.CharField(blank=True, max_length=50, null=True)),
                ('h_salida_str', models.CharField(blank=True, max_length=50, null=True)),
                ('id_hora_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.HoraEntrada')),
            ],
        ),
        migrations.AddField(
            model_name='horaentrada',
            name='idhorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.Horario'),
        ),
    ]
